import Head from "next/head";
// import { useState } from "react";
// import { Calendar } from "@/components/ui/calendar";
import Calendar from "@/components/Calendar";

export default function Home() {
  // const [date, setDate] = useState<Date | undefined>(new Date());

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* <Calendar
            mode="single"
            selected={date}
            onSelect={setDate}
            className="rounded-md border"
          /> */}
          <Calendar />
        </div>
      </main>
    </>
  );
}
